server:
  port: 8761
spring:
  application:
    name: eureka-server
    url: jdbc:mysql://localhst:3307/user_service_db

eureka:
  client:
    register-with-eureka: false
    fetch-register: false
defaultZone: http://localhost:8761/eureka/
