server:
  port: 8081
spring:
  application:
    name: user-service
    url: jdbc:mysql://localhst:3307/user_service_db
user:
  service:
    name: "User Service"
    version: "1.0"
    description: "사용자 정보 확인"